// Application Action Types

// Fetch Applications (paginated)
export const FETCH_APPLICATIONS_REQUEST = 'FETCH_APPLICATIONS_REQUEST';
export const FETCH_APPLICATIONS_SUCCESS = 'FETCH_APPLICATIONS_SUCCESS';
export const FETCH_APPLICATIONS_FAILURE = 'FETCH_APPLICATIONS_FAILURE';

// Fetch New Loan Applications
export const FETCH_NEW_APPLICATIONS_REQUEST = 'FETCH_NEW_APPLICATIONS_REQUEST';
export const FETCH_NEW_APPLICATIONS_SUCCESS = 'FETCH_NEW_APPLICATIONS_SUCCESS';
export const FETCH_NEW_APPLICATIONS_FAILURE = 'FETCH_NEW_APPLICATIONS_FAILURE';

// Clear Applications
export const CLEAR_APPLICATIONS = 'CLEAR_APPLICATIONS';
