// Bank Action Types

// Fetch Bank Accounts
export const FETCH_BANK_ACCOUNTS_REQUEST = 'FETCH_BANK_ACCOUNTS_REQUEST';
export const FETCH_BANK_ACCOUNTS_SUCCESS = 'FETCH_BANK_ACCOUNTS_SUCCESS';
export const FETCH_BANK_ACCOUNTS_FAILURE = 'FETCH_BANK_ACCOUNTS_FAILURE';

// Clear Bank Accounts
export const CLEAR_BANK_ACCOUNTS = 'CLEAR_BANK_ACCOUNTS';
