// Customer Action Types
export const FETCH_CUSTOMER_REQUEST = 'FETCH_CUSTOMER_REQUEST';
export const FETCH_CUSTOMER_SUCCESS = 'FETCH_CUSTOMER_SUCCESS';
export const FETCH_CUSTOMER_FAILURE = 'FETCH_CUSTOMER_FAILURE';

// Aadhaar Status Action Types
export const FETCH_AADHAAR_STATUS_REQUEST = 'FETCH_AADHAAR_STATUS_REQUEST';
export const FETCH_AADHAAR_STATUS_SUCCESS = 'FETCH_AADHAAR_STATUS_SUCCESS';
export const FETCH_AADHAAR_STATUS_FAILURE = 'FETCH_AADHAAR_STATUS_FAILURE';

// eSign Status Action Types
export const FETCH_ESIGN_STATUS_REQUEST = 'FETCH_ESIGN_STATUS_REQUEST';
export const FETCH_ESIGN_STATUS_SUCCESS = 'FETCH_ESIGN_STATUS_SUCCESS';
export const FETCH_ESIGN_STATUS_FAILURE = 'FETCH_ESIGN_STATUS_FAILURE';

// BRE Initialize Action Types
export const BRE_INITIALIZE_REQUEST = 'BRE_INITIALIZE_REQUEST';
export const BRE_INITIALIZE_SUCCESS = 'BRE_INITIALIZE_SUCCESS';
export const BRE_INITIALIZE_FAILURE = 'BRE_INITIALIZE_FAILURE';

// BSA Update Action Types
export const BSA_UPDATE_REQUEST = 'BSA_UPDATE_REQUEST';
export const BSA_UPDATE_SUCCESS = 'BSA_UPDATE_SUCCESS';
export const BSA_UPDATE_FAILURE = 'BSA_UPDATE_FAILURE';

// Loan Products Action Types
export const FETCH_LOAN_PRODUCTS_REQUEST = 'FETCH_LOAN_PRODUCTS_REQUEST';
export const FETCH_LOAN_PRODUCTS_SUCCESS = 'FETCH_LOAN_PRODUCTS_SUCCESS';
export const FETCH_LOAN_PRODUCTS_FAILURE = 'FETCH_LOAN_PRODUCTS_FAILURE';

// Finfactor Action Types
export const FETCH_FINFACTOR_REQUEST = 'FETCH_FINFACTOR_REQUEST';
export const FETCH_FINFACTOR_SUCCESS = 'FETCH_FINFACTOR_SUCCESS';
export const FETCH_FINFACTOR_FAILURE = 'FETCH_FINFACTOR_FAILURE';

// eSign Initialize Action Types
export const ESIGN_INITIALIZE_REQUEST = 'ESIGN_INITIALIZE_REQUEST';
export const ESIGN_INITIALIZE_SUCCESS = 'ESIGN_INITIALIZE_SUCCESS';
export const ESIGN_INITIALIZE_FAILURE = 'ESIGN_INITIALIZE_FAILURE';

// Bank Update Action Types
export const BANK_UPDATE_REQUEST = 'BANK_UPDATE_REQUEST';
export const BANK_UPDATE_SUCCESS = 'BANK_UPDATE_SUCCESS';
export const BANK_UPDATE_FAILURE = 'BANK_UPDATE_FAILURE';

// Clear/Reset Action Types
export const CLEAR_CUSTOMER_DATA = 'CLEAR_CUSTOMER_DATA';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
