// Loan Action Types

// Fetch Loan Status
export const FETCH_LOAN_STATUS_REQUEST = 'FETCH_LOAN_STATUS_REQUEST';
export const FETCH_LOAN_STATUS_SUCCESS = 'FETCH_LOAN_STATUS_SUCCESS';
export const FETCH_LOAN_STATUS_FAILURE = 'FETCH_LOAN_STATUS_FAILURE';

// Fetch Active Loan
export const FETCH_ACTIVE_LOAN_REQUEST = 'FETCH_ACTIVE_LOAN_REQUEST';
export const FETCH_ACTIVE_LOAN_SUCCESS = 'FETCH_ACTIVE_LOAN_SUCCESS';
export const FETCH_ACTIVE_LOAN_FAILURE = 'FETCH_ACTIVE_LOAN_FAILURE';

// Clear Loan Status
export const CLEAR_LOAN_STATUS = 'CLEAR_LOAN_STATUS';
