// Support Action Types

// Fetch Support Tickets
export const FETCH_SUPPORT_TICKETS_REQUEST = 'FETCH_SUPPORT_TICKETS_REQUEST';
export const FETCH_SUPPORT_TICKETS_SUCCESS = 'FETCH_SUPPORT_TICKETS_SUCCESS';
export const FETCH_SUPPORT_TICKETS_FAILURE = 'FETCH_SUPPORT_TICKETS_FAILURE';

// Clear Support Tickets
export const CLEAR_SUPPORT_TICKETS = 'CLEAR_SUPPORT_TICKETS';
